**Usando o markdown**

Markdown são usados para comentários e enunciados. Pesquise na web como usá-los

Nome: Leonardo Oliveira de Jesus ID: 12111EBi033

Eu ja utilizei o Markdown para entregar projetos ao longo do curso de Processamento de Sinais Biomedicos.
Inclusive, funciona muito bem e é bem prático


E importante tambem definir que os codigos foram alterados e devem ser rodados na ordem correta p[ara nao ocasionar erros nos exemplos ou nos criados


In [39]:
# iniciando com python
# https://www.facom.ufu.br/~wendelmelo/meu_material/introducao_programacao_python_wendel_melo.pdf

x = 2 +3
a = 1
print(x)
print(a)

5
1


In [82]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

x = 2 + 10
a = -2
print(x)
print(a)

12
-2


https://www.facom.ufu.br/~wendelmelo/pythontw201901/aula_numpy.txt

numerical python
o propósito do numpy é facilitar computação numérica, científica e matricial

Numpy disponibiliza duas classes principais:
array: array de qualquer dimensão
matrix: representa matrizes de duas dimensões (linhas e colunas)

Instalar o pacote (shell):
pip3 install -U numpy

import numpy as np
A = np.matrix(  [ [1,2], [3,4]  ]    )


In [41]:
import numpy as np
A = np.matrix(  [ [1,2 ,3 ,4 ], [5,6,7,8],[ 9,10,11,12]  ] )   
A

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [83]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033
import numpy as np
Matrix_Leo = np.matrix(  [ [1,0,0,0],[0,1,0,0],[0,0,0,1]  ] )   
Matrix_Leo

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1]])

In [43]:
#a variável A aponta para uma matriz de duas linhas e duas colunas
type(Matrix_Leo)


numpy.matrix

In [44]:
#acessando um elemento da matriz
print("Matrix")
print(A)
print("Acessos")
print(A[0, 1])#acessa o elemento na linha 0 e na coluna 1
print(A[1]) #acessa a linha 1 da matriz
print(A[1,:]) #acessa a linha 1 da matriz. Dois pontos significa "todas" - se na primeira dimensão, todas as linhas
print(A[:, 0])  #acessa toda a coluna 0 da matriz. Dois pontos significa "todas" - se na primeira dimensão, todas as linhas



Matrix
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Acessos
2
[[5 6 7 8]]
[[5 6 7 8]]
[[1]
 [5]
 [9]]


In [84]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033
print("Matrix")
print(A)
print("Acessos")
print(Matrix_Leo[0, 1])#acessa o elemento na linha 0 e na coluna 1
print(Matrix_Leo[1]) #acessa a linha 1 da matriz
print(Matrix_Leo[0,:]) #acessa a linha 1 da matriz. Dois pontos significa "todas" - se na primeira dimensão, todas as linhas
print(Matrix_Leo[:, 0])  #acessa toda a coluna 0 da matriz. Dois pontos significa "todas" - se na primeira dimensão, todas as linhas



Matrix
[[1 1 3]
 [2 3 3]
 [2 3 3]]
Acessos
0
[[0 1 0 0]]
[[1 0 0 0]]
[[1]
 [0]
 [0]]


In [46]:
#acessando um elemento da matriz com : (python slice) ==> inicio:fim:passo
# doc completa: https://docs.python.org/3/library/stdtypes.html#typesseq
# se início é omitido, fica com a coluna 0. Ex: :1:1
# se fim é omitido, vai até o final da dimensão. Ex 1::1
# se o passo é omitido, é assumido valor 1. Ex: 1:2
print("Matrix")
print(A)
print("Acesso [0:2,1]")
print(A[0:2, 1])#acessa o elemento na linha 0 até a linha 1 (ou seja, 2-1 = 1) e na coluna 1
print("Acessos [0:2,1:4:2]")
print(A[0:2, 1:4:2])#acessa o elemento na linha 0 até a linha 1 (ou seja, 2-1 = 1) e iniciando na coluna 1, pulando uma coluna  e indo até a colune 4-1=3
print("Mostrando a matriz com as linhas reversas")
print(A[::-1,:]) 



Matrix
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Acesso [0:2,1]
[[2]
 [6]]
Acessos [0:2,1:4:2]
[[2 4]
 [6 8]]
Mostrando a matriz com as linhas reversas
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [85]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#acessando um elemento da matriz com : (python slice) ==> inicio:fim:passo
# doc completa: https://docs.python.org/3/library/stdtypes.html#typesseq
# se início é omitido, fica com a coluna 0. Ex: :1:1
# se fim é omitido, vai até o final da dimensão. Ex 1::1
# se o passo é omitido, é assumido valor 1. Ex: 1:2
print("Matrix")
print(Matrix_Leo)
print("Acesso [0:2,1]")
print(Matrix_Leo[0:2, 1])#acessa o elemento na linha 0 até a linha 1 (ou seja, 2-1 = 1) e na coluna 1
print("Acessos [0:2,1:4:2]")
print(Matrix_Leo[0:2, 1:4:2])#acessa o elemento na linha 0 até a linha 1 (ou seja, 2-1 = 1) e iniciando na coluna 1, pulando uma coluna  e indo até a colune 4-1=3
print("Mostrando a matriz com as linhas reversas")
print(Matrix_Leo[::-1,:]) 



Matrix
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]]
Acesso [0:2,1]
[[0]
 [1]]
Acessos [0:2,1:4:2]
[[0 0]
 [1 0]]
Mostrando a matriz com as linhas reversas
[[0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]]


In [48]:

#a função zeros gera um array de zeros
Z = np.zeros(  (4,5)    )
Z


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#a função zeros gera um array de zeros
zerosLeo = np.zeros(  (3,3)    )
zerosLeo


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
#podemos gerar matrizes de números aleatórios
import numpy.random as npr
N = np.matrix(   npr.randint(-10, 10, (3, 2)  )    )  #gera matriz de numeros inteiros aleatorios entre -10 e 10, tendo 3 linhas e 2 colunas
N

matrix([[ -1,  -4],
        [-10,   1],
        [ -7,  -7]], dtype=int32)

In [87]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#podemos gerar matrizes de números aleatórios
import numpy.random as npr
N_leo = np.matrix(   npr.randint(-10, 10, (3, 2)  )    )  #gera matriz de numeros inteiros aleatorios entre -10 e 10, tendo 3 linhas e 2 colunas
N_leo

matrix([[ -1,  -4],
        [ -1,  -8],
        [-10,   3]], dtype=int32)

In [52]:
#gernado outra matriz
N = np.matrix(   npr.randint(-10, 10, (3, 2)  )    )  #gera matriz de numeros inteiros aleatorios entre -10 e 10, tendo 3 linhas e 2 colunas
N


matrix([[ -8,  -1],
        [ -2, -10],
        [  6,   3]], dtype=int32)

In [88]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#gernado outra matriz
N1_Leo = np.matrix(   npr.randint(-10, 10, (3, 2)  )    )  #gera matriz de numeros inteiros aleatorios entre -10 e 10, tendo 3 linhas e 2 colunas
N1_Leo


matrix([[-5, -6],
        [-1,  9],
        [-6, -7]], dtype=int32)

In [54]:
# Lembre que python é orientado a objetos. Assim uma simples atribuições entre duas matrizes faz com que abas apontem para o mesmo objeto
B=A
print(A)
print(B)

print("Mudando o valor de A - veja que B foi modificado também")
A[0,0] = -100
print(A)
print(B)

print("Mudando o valor de B - veja que A foi modificado também")
B[0,0] = 30
print(A)
print(B)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mudando o valor de A - veja que B foi modificado também
[[-100    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
[[-100    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Mudando o valor de B - veja que A foi modificado também
[[30  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[30  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [89]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

# Lembre que python é orientado a objetos. Assim uma simples atribuições entre duas matrizes faz com que abas apontem para o mesmo objeto
B=A
print(A)
print(B)

print("Mudando o valor de A - veja que B foi modificado também")
A[0,0] = 1
print(A)
print(B)

print("Mudando o valor de B - veja que A foi modificado também")
B[0,0] = 2
print(A)
print(B)



[[1 1 3]
 [2 3 3]
 [2 3 3]]
[[1 1 3]
 [2 3 3]
 [2 3 3]]
Mudando o valor de A - veja que B foi modificado também
[[1 1 3]
 [2 3 3]
 [2 3 3]]
[[1 1 3]
 [2 3 3]
 [2 3 3]]
Mudando o valor de B - veja que A foi modificado também
[[2 1 3]
 [2 3 3]
 [2 3 3]]
[[2 1 3]
 [2 3 3]
 [2 3 3]]


In [56]:
# podemos criar uma matriz copiando de uma outra matriz,
C = np.matrix(A)
print(A)
print(C)
print("Mudando o valor de A - veja que C não será afetada")
A[0,0] = 50;
print(A)
print(C)


print("Mudando o valor de C - veja que A não será afetada")
C[0,0] = 100;
print(A)
print(C)

[[ 2  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mudando o valor de A - veja que C não será afetada
[[50  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mudando o valor de C - veja que A não será afetada
[[50  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [90]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

# podemos criar uma matriz copiando de uma outra matriz,

A[0,0] = 100000; #a nao ser que sejaa mudado antes

C = np.matrix(A)
print(A)
print(C)
print("Mudando o valor de A - veja que C não será afetada")
A[0,0] = 50;
print(A)
print(C)


print("Mudando o valor de C - veja que A não será afetada")
C[0,0] = 100;
print(A)
print(C)

[[100000      1      3]
 [     2      3      3]
 [     2      3      3]]
[[100000      1      3]
 [     2      3      3]
 [     2      3      3]]
Mudando o valor de A - veja que C não será afetada
[[50  1  3]
 [ 2  3  3]
 [ 2  3  3]]
[[100000      1      3]
 [     2      3      3]
 [     2      3      3]]
Mudando o valor de C - veja que A não será afetada
[[50  1  3]
 [ 2  3  3]
 [ 2  3  3]]
[[100   1   3]
 [  2   3   3]
 [  2   3   3]]


In [58]:
#podemos operar com blocos de matrizes
M = np.matrix(Z)
print("Matriz M: ")
print(M)
print("Matriz N: ")
print(N)
#M[ 0:3,  2:4  ] = N
M[ 0:3,  0:3:2  ] = N
print("Matriz M após a atribuição em bloco: da linha zero até a linha 3, da coluna 2 até a 4 ")
print(M)

Matriz M: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matriz N: 
[[ -8  -1]
 [ -2 -10]
 [  6   3]]
Matriz M após a atribuição em bloco: da linha zero até a linha 3, da coluna 2 até a 4 
[[ -8.   0.  -1.   0.   0.]
 [ -2.   0. -10.   0.   0.]
 [  6.   0.   3.   0.   0.]
 [  0.   0.   0.   0.   0.]]


In [91]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033



#podemos operar com blocos de matrizes
M = np.matrix(Z)
print("Matriz M: ")
print(M)
print("Matriz N: ")
print(N)
#M[ 0:3,  2:4  ] = N
M[ 0:3,  0:3:2  ] = N
print("Matriz M após a atribuição em bloco: da linha zero até a linha 3, da coluna 2 até a 4 ")
print(M)

Matriz M: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matriz N: 
[[ -8  -1]
 [ -2 -10]
 [  6   3]]
Matriz M após a atribuição em bloco: da linha zero até a linha 3, da coluna 2 até a 4 
[[ -8.   0.  -1.   0.   0.]
 [ -2.   0. -10.   0.   0.]
 [  6.   0.   3.   0.   0.]
 [  0.   0.   0.   0.   0.]]


In [60]:
#podemos fazer operações diversas com matrizes
#criando uma matriz identidade (coluna com diagonal igual a 1)
B = np.matrix(   np.eye(2,2)    )
print(B)
print(np.matrix(   np.eye(10,10)    ))



[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [92]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#podemos fazer operações diversas com matrizes
#criando uma matriz identidade (coluna com diagonal igual a 1)
B = np.matrix(   np.eye(3,3)    )
print(B)
print(np.matrix(   np.eye(5,5)    ))



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [78]:
A = np.matrix([[1 ,1], [2 ,3] ])
print(A)
print(B)
#multiplicando a matriz B por um escalar
B = 4*B
B



[[1 1]
 [2 3]]
[[1024.    0.    0.]
 [   0. 1024.    0.]
 [   0.    0. 1024.]]


matrix([[4096.,    0.,    0.],
        [   0., 4096.,    0.],
        [   0.,    0., 4096.]])

In [93]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

A = np.matrix([[1 ,1], [2 ,3]])
print(A)
print(B)
#multiplicando a matriz B por um escalar
B = 4*B
B
A = 2*A
A



[[1 1]
 [2 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


matrix([[2, 2],
        [4, 6]])

In [79]:
#somando matrizes
print(A)
print(B)

C =  A + B
C


[[1 1]
 [2 3]]
[[4096.    0.    0.]
 [   0. 4096.    0.]
 [   0.    0. 4096.]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [94]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#somando matrizes
A = np.matrix([[1 ,1,3], [2 ,3,3],[2 ,3,3]])
print(A)
print(B)

C =  A + B
C


[[1 1 3]
 [2 3 3]
 [2 3 3]]
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]


matrix([[5., 1., 3.],
        [2., 7., 3.],
        [2., 3., 7.]])

In [66]:
#multiplicando matrizes

print(A)
print(B)

D = A * B
D


[[2 2]
 [4 6]]
[[16.  0.  0.]
 [ 0. 16.  0.]
 [ 0.  0. 16.]]


ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [95]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#multiplicando matrizes

print(A)
print(B)

D = A * B
D


[[1 1 3]
 [2 3 3]
 [2 3 3]]
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]


matrix([[ 4.,  4., 12.],
        [ 8., 12., 12.],
        [ 8., 12., 12.]])

In [67]:
#podemos calcular potencia de matrizes

print(A)
print(B)

E = A**2 #equivale a E = A * A (multiplica a matriz por ela mesma)
E


[[2 2]
 [4 6]]
[[16.  0.  0.]
 [ 0. 16.  0.]
 [ 0.  0. 16.]]


matrix([[12, 16],
        [32, 44]])

In [96]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#podemos calcular potencia de matrizes

print(A)
print(B)

E = A**2 #equivale a E = A * A (multiplica a matriz por ela mesma)
E


[[1 1 3]
 [2 3 3]
 [2 3 3]]
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]


matrix([[ 9, 13, 15],
        [14, 20, 24],
        [14, 20, 24]])

In [68]:
#podemos calcular a inversa de uma matriz

print(A)
Ainversa = A**-1
print(Ainversa)
print(A * Ainversa)


[[2 2]
 [4 6]]
[[ 1.5 -0.5]
 [-1.   0.5]]
[[1. 0.]
 [0. 1.]]


In [99]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#podemos calcular a inversa de uma matriz
A = np.matrix([[1 ,1,3], [2 ,3,3],[2 ,4,3]])

print(A)
Ainversa = A**-1
print(Ainversa)
print(A * Ainversa)


[[1 1 3]
 [2 3 3]
 [2 4 3]]
[[-1.          3.         -2.        ]
 [ 0.         -1.          1.        ]
 [ 0.66666667 -0.66666667  0.33333333]]
[[ 1.00000000e+00  1.11022302e-16 -5.55111512e-17]
 [-1.11022302e-16  1.00000000e+00 -5.55111512e-17]
 [-1.11022302e-16  1.11022302e-16  1.00000000e+00]]


In [69]:
#podemos calcular a matriz transposta
A
print(A)
print(np.transpose(A))


[[2 2]
 [4 6]]
[[2 4]
 [2 6]]


In [100]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#podemos calcular a matriz transposta
A
print(A)
print(np.transpose(A))


[[1 1 3]
 [2 3 3]
 [2 4 3]]
[[1 2 2]
 [1 3 4]
 [3 3 3]]


In [70]:
#a função trace que calcula o traço da matriz (a soma dos elementos da diagonal principal)

print(A)
np.trace(A)


[[2 2]
 [4 6]]


np.int64(8)

In [101]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#a função trace que calcula o traço da matriz (a soma dos elementos da diagonal principal)

print(A)
np.trace(A)


[[1 1 3]
 [2 3 3]
 [2 4 3]]


np.int64(7)

In [71]:
#podemos concatenar matrizes
#por coluna: hstack

print(A)
print(B)
np.hstack( (A, B) )


[[2 2]
 [4 6]]
[[16.  0.  0.]
 [ 0. 16.  0.]
 [ 0.  0. 16.]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [102]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#podemos concatenar matrizes
#por coluna: hstack

print(A)
print(B)
np.hstack( (A, B) )


[[1 1 3]
 [2 3 3]
 [2 4 3]]
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]


matrix([[1., 1., 3., 4., 0., 0.],
        [2., 3., 3., 0., 4., 0.],
        [2., 4., 3., 0., 0., 4.]])

In [72]:
#concatenando por linhas (vertical): vstack

print(A)
print(B)
np.vstack(  (A,B)   )


[[2 2]
 [4 6]]
[[16.  0.  0.]
 [ 0. 16.  0.]
 [ 0.  0. 16.]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [103]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#concatenando por linhas (vertical): vstack

print(A)
print(B)
np.vstack(  (A,B)   )


[[1 1 3]
 [2 3 3]
 [2 4 3]]
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]


matrix([[1., 1., 3.],
        [2., 3., 3.],
        [2., 4., 3.],
        [4., 0., 0.],
        [0., 4., 0.],
        [0., 0., 4.]])

In [73]:
#existem funções que se aplicam a todos os elementos de uma matriz

print(A)

np.sqrt(A)


[[2 2]
 [4 6]]


matrix([[1.41421356, 1.41421356],
        [2.        , 2.44948974]])

In [104]:
#Nome: Leonardo Oliveira de Jesus ID: 12111EBI033

#existem funções que se aplicam a todos os elementos de uma matriz

print(A)

np.sqrt(A)


[[1 1 3]
 [2 3 3]
 [2 4 3]]


matrix([[1.        , 1.        , 1.73205081],
        [1.41421356, 1.73205081, 1.73205081],
        [1.41421356, 2.        , 1.73205081]])